[build]
  publish = "public/"
  command = "gatsby build --prefix-paths && -d public -b master"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "10.15.1"
